### ISSUE TITLE
BUG: Sensitive JDBC data was exposed publicly 

### ISSUE THREAD

**Issue by aravindb26** [google/shifter#122]
Hi team, Hope u doing well :)

I have found a bug or we can say it's an issue that sensitive data was exposed publicly which causes a high advantage to an attacker.

Because JDBC is an application programming interface (API) for the programming language Java, which defines how a client may access a database. It is a Java-based data access technology used for Java database connectivity. It is part of the Java Standard Edition platform, from Oracle Corporation.

For an attacker, it becomes easier to access the database belonging to this repository

<img width="413" alt="gg__" src="https://user-images.githubusercontent.com/89305482/191069216-b7713cfb-a41e-4702-8d40-7649605cd13e.png">

**Comment by garybowers** [comment]
Thanks for raising however the clusters provisioned are automatically span up / down for pipeline testing in a private repo - this doesn't affect the application in any way.

**Comment by aravindb26** [comment]
> Thanks for raising however the clusters provisioned are automatically span up / down for pipeline testing in a private repo - this doesn't affect the application in any way.

you welcome 🙂. However it's revealing the username and password know? Like attacker might get access if in case if any bypass works??

**Comment by garybowers** [comment]
This isn't a issue it's just a DB connection for a demo application that runs for 10 mins on the cluster :) then the whole thing is torn down.

**Comment by aravindb26** [comment]
> This isn't a issue it's just a DB connection for a demo application that runs for 10 mins on the cluster :) then the whole thing is torn down.

Ok 🙂
