### ISSUE TITLE
https://shifter.cloud/

### ISSUE THREAD

**Issue by rahul2333** [google/shifter#38]
When using UI to convert from Openshift to Kubernetes getting constant error

![Shifter](https://user-images.githubusercontent.com/26868695/162772573-fce9d675-9995-4ef8-bb90-21beab7f8afa.png)

**Comment by garybowers** [comment]
Hi would you be open to sharing the manifest file you are using?

**Comment by timbohiatt** [comment]
Hey @rahul2333, In addition to @garybowers suggestion of sharing the manifest file I thought it would be a good idea to highlight that the UI is an experimental feature right now that is still very much "pre-alpha" the fact that you have found it is actually super exciting for us as we have hardly advertised this tool let alone the UI. 

We would be happy to keep you posted on the continued development of the UI and as soon as it is working we would love for you to try again.

Until that time you could also download the latest CLI version of Shifter and run it locally. 
I have provided the Linux and Windows Builds of v0.2.0 to this comment as links: 

If you would prefer you can download and build from source anytime you like. 

In addition the Docker Container Image of v0.2.0 should be available in the next few days. I will post back here when those details are available. 

Linux Build v0.2.0:
https://storage.googleapis.com/shifter-lz-002-prd-shifter-builds/binary/v0.2.0/shifter_linux_amd64

Windows Build v0.2.0:
https://storage.googleapis.com/shifter-lz-002-prd-shifter-builds/binary/v0.2.0/shifter_win_amd64.exe

**Comment by timbohiatt** [comment]
@rahul2333 
As of now. I have configured the container registry for shifter if it would be of interest you can also now pull the Shifter CLI as a container `docker pull images.shifter.cloud/shifter:v0.2.0`

**Comment by rahul2333** [comment]
@garybowers  I have used the same files which are available under _test folder !

**Comment by rahul2333** [comment]
Hey @timbohiatt , appreciate your response in providing the details of CLI version of Shifter which helped me in converting those manifest files locally 👍  Thank you for publising the image will give it a try on that as well 👍

**Comment by timbohiatt** [comment]
Absolutely no problems @rahul2333. I hope it helped. This project, as I said is very much in its infancy but we are building it for long term success and welcome contribution and discussions. 

Just yesterday we released a minor patch that now allows for container images which can be run locally which maybe helpful. You can find the ReadMe now has some basic examples. To get the latest image simply... 

docker pull images.shifter.cloud/shifter

I'll get back to you here as soon as we get the UI at https://shifter.cloud up and running again! We are hoping for a release to fix that in next 3 or so weeks. 

Cheers!

**Comment by phani-boppana2020** [comment]
> 

I see the links for Linux and Windows exe files are down, can you please confirm when these will be up again ?

**Comment by timbohiatt** [comment]
@phani-boppana2020 .. Thanks for pointing that out. We are aware they are not updating at this point. We will manually issue the v0.2.5 release as soon as we can (hopefully today) and report back here. 

We are in the process of bringing this Repo together with the UI Repo and while we are pre v1.0.0 we hope you all understand a little disruption while we build out our ways of working and contribution. 

Thanks again for your feedback and contribution.

**Comment by garybowers** [comment]
@phani-boppana2020 The binaries should be available here https://github.com/google/shifter/releases/tag/v0.2.5

Hope you find it useful, if you find any issues or would like to see any features feel free to raise a issue here!! 

Gary

**Comment by timbohiatt** [comment]
@rahul2333 ... It has been a long time coming. Apologies for that. However the site is now fixed, working and possible for demo with a cluster that has access to the public internet. Please let us know if you have any further issues. 

Tim.
