### ISSUE TITLE
terminal stuck after executing the command sh build-deploy-local.sh 

### ISSUE THREAD

**Issue by HIMANSHU17GAUR** [google/shifter#76]
![shifter1](https://user-images.githubusercontent.com/9974989/172224802-e7344fd2-8cce-40f8-b402-c979a045ab27.PNG)

terminal stuck after executing the command sh build-deploy-local.sh 

logs:

,[re(s,{to:"/"},{default:De(()=>[uf]),_:1}),re(s,{to:"/about"},{default:De(()=>[ff]),_:1}),af])])]),re(of)],64)}}}),pf=wu({history:jc("/"),routes:[{path:"/",name:"home",component:hf},{path:"/about",name:"about",component:()=>Bn(()=>import("./AboutView.8e100392.js"),["assets/AboutView.8e100392.js","assets/AboutView.ab071ea6.css"])},{path:"/status/healthz",name:"healthz",component:()=>Bn(()=>import("./HealthzView.39e8f622.js"),["assets/HealthzView.39e8f622.js","assets/HealthzView.dedbb70f.css","assets/index.15c82977.js"])},{path:"/status/settingz",name:"settingz",component:()=>Bn(()=>import("./SettingzView.47290ae2.js"),["assets/SettingzView.47290ae2.js","assets/SettingzView.64984f6c.css","assets/index.15c82977.js"])}]});const mf="http://localhost:9091/api/v1";var gf={SHIFTER_SERVER_ENDPOINT:mf};const Gt=hc(Ru),_f=gc();Gt.config.globalProperties.$shifterConfig={API_BASE_URL:gf.SHIFTER_SERVER_ENDPOINT};Gt.use(_f);Gt.use(pf);Gt.mount("#app");const Ef=Gt.config.globalProperties.$shifterConfig;export{wr as D,In as _,ue as a,vf as b,at as c,bf as d,bo as e,re as f,Uu as g,Ce as h,yf as m,We as o,Ef as s,Qo as t,xt as u,De as w};
shifter_server_development | [GIN] 2022/06/06 - 17:46:58 | 404 |        3.75µs |      172.19.0.1 | GET      "/"
shifter_server_development | [GIN] 2022/06/06 - 17:47:13 | 404 |       1.389µs |      172.19.0.1 | GET      "/"
shifter_server_development | [GIN] 2022/06/06 - 17:47:59 | 404 |         6.4µs |      172.19.0.1 | GET      "/"

**Comment by timbohiatt** [comment]
Hello @HIMANSHU17GAUR . Thanks for taking the time to report the issue. Could you please provide a little more context. Based on what I can see above the terminal is not stuck but rather you are running the application with the UI locally therefore you would need to hit http://localhost:9090 

What you are seeing in the terminal is the live running containers for the Shifter-UI and Shifter Server. 
Please let us know what you find and feel free to let us know if this does not resolve your issue. 

Also please note we are currently working on v0.3.0 which should bring a greater level of stability to the whole tool.

**Comment by timbohiatt** [comment]
@HIMANSHU17GAUR since your original comments back in June the team have made some major changes and multiple releases since. There is now a working version on the [https://shifter.cloud](public website). As a result of this I will close this comment as I believe the initial raise and issue has been both responded to and is also no longer top of mind.
